### ISSUE TITLE
Can't get sessionId by OAuth

### ISSUE THREAD

**Issue by kutear** [appwrite/sdk-for-flutter#28] opened 2021-07-19 18:32 UTC
When login with createOAuth2Session(...), the `Response` is null. and there is no way to get sessionId.

``` dart
// login code
var sessionId = ""
account.createOAuth2Session(provider: provider)
.then((value) {
       // value is null
       sessionId = ""; // TODO
});


// logout code
account.deleteSession(sessionId: sessionId)

```
only `getSessions` can get all sessions, but i don't know which session is my current session.

**Comment by TorstenDittmann** [comment] 2021-07-19 18:46
You can use [getSession('current')](https://appwrite.io/docs/client/account#accountGetSession) to get the current session 👍🏻

**Comment by kutear** [comment] 2021-07-20 03:36
> You can use [getSession('current')](https://appwrite.io/docs/client/account#accountGetSession) to get the current session 👍🏻

I know i can get session by current sessionId, but my question is i can't get current sessionId.

**Comment by TorstenDittmann** [comment] 2021-07-20 07:14
You can just pass 'current' to the method and it will return your current session 👍

**Comment by kutear** [comment] 2021-07-20 08:43
> You can just pass 'current' to the method and it will return your current session 👍

Oh, I got it.  thanks!

**Comment by kutear** [comment] 2021-08-05 04:56
> You can just pass 'current' to the method and it will return your current session

it's not work for me. when i pass `current` to `getSession(...)`, it return all sessions, just same as `getSessions()` .

![Screenshot from 2021-08-05 12-54-54_mosaic](https://user-images.githubusercontent.com/8605389/128293069-d3c94f0b-d207-4b1b-8516-743bb1cc0c24.png)

**Comment by lohanidamodar** [comment] 2021-08-08 07:42
@kutear I am unable to reproduce the issue, I am not sure, what is causing this for you.
I order to verify, I suggest you run the code on Flutter web and see the actual request in the browser console's network Tab and Please get back to us if there again you get all the sessions.

**Comment by lohanidamodar** [comment] 2021-08-08 07:46
@kutear can you share which version of Appwrite Server you are using?

**Comment by kutear** [comment] 2021-08-09 03:52
> @kutear can you share which version of Appwrite Server you are using?

server: v:0.8.0.146
client: sdk-for-flutter 0.7.1

**Comment by TorstenDittmann** [comment] 2021-08-20 16:29
> > @kutear can you share which version of Appwrite Server you are using?
> 
> server: v:0.8.0.146
> client: sdk-for-flutter 0.7.1

Are you able to upgrade Appwrite and the Flutter SDK to the latest version? This might fix it.

More informations about upgrading: https://appwrite.io/docs/upgrade

**Comment by lohanidamodar** [comment] 2021-09-09 10:08
@kutear closing this as there was no further response. If you still have this issue, please feel free to reopen the issue.

**Closed by lohanidamodar** 2021-09-09 10:08 UTC
