### ISSUE TITLE
🐛 Bug Report: Missing null check in Document.fromMap factory

### ISSUE THREAD

**Issue by joern-h** [appwrite/sdk-for-flutter#175] opened 2023-09-15 09:30 UTC
### 👟 Reproduction steps

Databases listDocuments with select query that does not include $permissions field

### 👍 Expected behavior

Document object should be constructed with an empty $permissions list

Proposed change:
```
  factory Document.fromMap(Map<String, dynamic> map) {
    return Document(
      $id: map['\$id'].toString(),
      $collectionId: map['\$collectionId'].toString(),
      $databaseId: map['\$databaseId'].toString(),
      $createdAt: map['\$createdAt'].toString(),
      $updatedAt: map['\$updatedAt'].toString(),
      $permissions: map['\$permissions'] ?? [], // add null check
      data: map,
    );
  }
```

### 👎 Actual Behavior

factory Document.fromMap throws exception: 'Null' is not a subtype of type 'List<dynamic>'

```
  factory Document.fromMap(Map<String, dynamic> map) {
    return Document(
      $id: map['\$id'].toString(),
      $collectionId: map['\$collectionId'].toString(),
      $databaseId: map['\$databaseId'].toString(),
      $createdAt: map['\$createdAt'].toString(),
      $updatedAt: map['\$updatedAt'].toString(),
      $permissions: map['\$permissions'], // null exception 
      data: map,
    );
  }
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.4.2
Flutter SDK: 11.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joern-h** [comment] 2023-09-20 08:45
This is related to https://github.com/appwrite/appwrite/issues/6158

**Comment by stnguyen90** [comment] 2024-08-14 05:14
Closing as duplicate of https://github.com/appwrite/appwrite/issues/6158

**Closed by stnguyen90** 2024-08-14 05:14 UTC
Labels: bug
