### ISSUE TITLE
redirect_uri_mismatch when use Google oAuth

### ISSUE THREAD

**Issue by eeqdevv** [appwrite/sdk-for-flutter#161] opened 2023-07-12 05:11 UTC
I self hosting the appwrite then when use google oAuth shows **redirect_uri_mismatch status code :400**.
how i solf this problem ?
used flutter sdk as client side
<img width="373" alt="Screenshot 2023-07-12 at 10 54 07 AM" src="https://github.com/soodoku/tuber/assets/44582949/4b4aecc7-353b-4392-a9fa-835bcebc52db">

**Comment by joeyouss** [comment] 2023-07-12 13:44
Hi, this seems like duplicate of https://github.com/appwrite/appwrite/issues/5806

I am going to close this once and keep that issue open for resolution

**Closed by joeyouss** 2023-07-12 13:44 UTC
