### ISSUE TITLE
🚀 Feature: creating and deleting collection

### ISSUE THREAD

**Issue by hemangjoshi37a** [appwrite/sdk-for-flutter#126] opened 2023-03-04 13:58 UTC
### 🔖 Feature description

creating and deleting collection

### 🎤 Pitch

creating and deleting collection

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-03-07 19:51
Closing duplicate of https://github.com/appwrite/appwrite/discussions/5193

**Closed by stnguyen90** 2023-03-07 19:51 UTC
