### ISSUE TITLE
🐛 - User Object gives an error

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [appwrite/sdk-for-flutter#33] opened 2021-09-25 16:09 UTC
### Issue description:
when I execute `User _response = await Connection.instance.account.get();`, it gives an error:

```
E/flutter ( 6728): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'List<dynamic>' is not a subtype 
of type 'Map<String, dynamic>'
E/flutter ( 6728): #0      new User.fromMap (package:appwrite/src/models/user.dart:49:37)
E/flutter ( 6728): #1      Account.get (package:appwrite/services/account.dart:21:24)
E/flutter ( 6728): <asynchronous suspension>
E/flutter ( 6728): #2      UserModel.setUserData (package:expirapp/models/UserModel.dart:215:21) <- the mentioned line of code
E/flutter ( 6728): <asynchronous suspension>
```

I suppose the cause of this issue is that the resposne map in `account.dart:19`:
```dart
final res = await client.call(HttpMethod.get, path: path, params: params, headers: headers); 
```
is a map with a key "prefs" -> List:
![image](https://user-images.githubusercontent.com/19879399/134778076-7f871806-2dde-4070-bd01-9799fde54454.png)
Which later, in `user.dart:41`: 
```dart
    return User(
      $id: map['\$id'],
      name: map['name'],
      registration: map['registration'],
      status: map['status'],
      passwordUpdate: map['passwordUpdate'],
      email: map['email'],
      emailVerification: map['emailVerification'],
      prefs: Preferences.fromMap(map['prefs']),
    );
```
gets treated as a map.

**Comment by lohanidamodar** [comment] 2021-09-26 04:45
@dawid-niedzwiecki Can you please share the Appwrite Server version you are using?

**Comment by dawid-niedzwiecki** [comment] 2021-09-26 14:43
> @dawid-niedzwiecki Can you please share the Appwrite Server version you are using?

It's 0.10.4:
![Screenshot_2021-09-26-16-39-03-340_com android chrome](https://user-images.githubusercontent.com/19879399/134812556-a598c3bb-57b6-4b9b-a8ba-78ae892cd4a8.jpg)

**Comment by dawid-niedzwiecki** [comment] 2021-09-26 23:06
### Update

It came out, that it actually does work properly on newly created accounts. The issue happened on an account, that was created on a previous version of the Appwrite server. After deleting that account and creating a new one, the error didn't show up anymore.

**Comment by lohanidamodar** [comment] 2021-09-27 00:48
> ### Update
> It came out, that it actually does work properly on newly created accounts. The issue happened on an account, that was created on a previous version of the Appwrite server. After deleting that account and creating a new one, the error didn't show up anymore.

Could be a migration bug. We will take a look into it.

**Comment by stnguyen90** [comment] 2021-09-27 22:15
@dawid-niedzwiecki, was your account originally created via OAuth2?

**Comment by lohanidamodar** [comment] 2022-02-11 05:58
Closing this, as this should be fixed in the newer versions of SDK and Appwrite, if not feel free to reopen the issue.

**Closed by lohanidamodar** 2022-02-11 05:58 UTC

**Comment by jonscoresby** [comment] 2022-11-08 17:43
I'm new to Appwrite so hopefully this isn't out of place. I am using the latest versions of Appwrite server and SDK and I am getting this error. I have a realtime subscription to the account channel. The account channel returns a User object instead of an Account object. Not sure exactly why that is. Anyway, I try to pass the response to the Account.fromMap() constructor and I get the error given in this issue. It seems that the prefs attribute in the User object returns a List instead of a map. If I understand correctly, what use to be a User object is now an Account object and the Account response works correctly, but I am getting a User response where the prefs attribute is still the wrong type. 

I'm not sure if this behavior is considered an error or not, but I'd thought I'd mention it. Perhaps I'm not using the application as intended.

**Comment by stnguyen90** [comment] 2022-11-08 19:06
@jonscoresby it might be best to either create a new issue or join us on [Discord](https://appwrite.io/discord). If you want to create an issue, please make sure to include you code, full error, and the response from Appwrite. 🙏🏼
