### ISSUE TITLE
🐛 Bug Report: AppwriteException: null, Concurrent modification during iteration: Instance(length:2) of '_GrowableList'. (0)

### ISSUE THREAD

**Issue by anandsubbu007** [appwrite/sdk-for-flutter#103] opened 2022-03-26 11:52 UTC
### 👟 Reproduction steps

when i tried to log in session.

### 👍 Expected behavior

-

### 👎 Actual Behavior

AppwriteException: null, Concurrent modification during iteration: Instance(length:2) of '_GrowableList'. (0)

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Flutter

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2022-10-14 16:07
@nohli, @p4-k4, are you still having problems with the latest SDK?

**Comment by nohli** [comment] 2022-10-14 16:16
@stnguyen90 for me it's fixed since `appwrite: ^7.0.0` 👍🏽

**Comment by kekavc24** [comment] 2022-11-16 07:15
I can confirm it was fixed in flutter windows too. I had opened #59 as duplicate. @stnguyen90. So I assume @anandsubbu007 's was fixed too

**Closed** 2022-11-16 20:25 UTC
Labels: bug
