### ISSUE TITLE
🚀 Feature: Listen to auth changes

### ISSUE THREAD

**Issue by HosamHasanRamadan** [appwrite/sdk-for-flutter#143] opened 2023-04-17 12:29 UTC
### 🔖 Feature description

Listen to auth changes like in Firebase and Supabase
**Firebase** 
` FirebaseAuth.instance.authStateChanges() `
 **Supabase** 
`supabase.auth.onAuthStateChange`

### 🎤 Pitch

There is no way right now to redirect the user immediately if the session is expired. In this case, all the requests will fail. 

In `Account` class, we should add this function:
`Stream<User?> getAuthStateChanges()`
if `User` is null = `NotAuthinticated`

The problem is that I don't know the feasibility of this feature from app write backend perspective 

Currently, I implemented terrible workaround for this missing feature, I call `Account.get()` every one second to get fresh user state changes
```dart
Stream.periodic(
  const Duration(seconds: 1),
  (_) {
    try {
      awAccount.get();
      print('User is signed in');
    } catch (e, s) {
      print('User is signed out');
    }
  },
);
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-04-18 17:47
Thanks for opening this issue! 🙏🏼 This looks like a duplicate of https://github.com/appwrite/sdk-for-flutter/issues/68. Please feel free to 👍🏼 the other issue.

**Closed by stnguyen90** 2023-04-18 17:47 UTC
