### ISSUE TITLE
🚀 Feature: Json as datatype of attributes

### ISSUE THREAD

**Issue by DobreRadu** [appwrite/sdk-for-flutter#122] opened 2023-02-09 10:57 UTC
### 🔖 Feature description

I believe JSON should be an option when creating an attribute.

### 🎤 Pitch

I find myself often to create an array of String and storing jsons and parsing them in flutter and when saving also to convert them to string and so on.
Json is amazing in my point of view and I often use it to store data.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-02-09 23:03
@DobreRadu, thanks for creating this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/2735? If so, would you please 👍🏼 that issue and close this one as a duplicate?

**Closed** 2023-02-10 06:13 UTC
